spring:
  datasource:
    #数据库配置
    url: jdbc:mysql://192.168.2.60:3306/cloud_dream_lake?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # xml文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名包扫描
  type-aliases-package: com.taoyuan.learning
  # 配置文件位置
#  config_location: classpath:mybatis-config.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true