server:
  port: 9933


management:
  server:
    port: 9997
  endpoint:
    health:
      show-details: always  # 显示详细健康信息（生产环境慎用）
      enabled: true
    beans:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
#        include: health,metrics,info,env # 显式暴露端点
#        exclude: heap dump,thread dump # 排除敏感端点
#      base-path: /manage #  自定义基础路径（默认/actuator）
spring:
  profiles:
    include:
      - jackson
      - hikaricp
      - common
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always



